# Use a Rust base image
FROM rust:latest

# Set the working directory
WORKDIR /app

# Copy the application source code into the container
COPY . .

# Build the application
RUN cargo build --release

# Run the application
CMD ["./target/release/listener"]
